//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Capl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema targetNamespace=&quot;http://schemas.authz.org/capl&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://schemas.authz.org/capl&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;AuthorizationPolicy&quot; type=&quot;AuthorizationPolicyType&quot; /&gt;
        ///  &lt;xs:element name=&quot;LogicalAnd&quot; type=&quot;LogicalConnectiveType&quot; /&gt;
        ///  &lt;xs:element name=&quot;LogicalOr&quot; type=&quot;LogicalConnectiveType&quot; /&gt;
        ///  &lt;xs:element name=&quot;Rule&quot; type=&quot;RuleType&quot; /&gt;
        ///  &lt;xs:element name=&quot;Operation&quot; type=&quot;OperationType&quot; /&gt;
        ///  &lt;xs:element na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthorizationPolicySchema {
            get {
                return ResourceManager.GetString("AuthorizationPolicySchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xs:schema targetNamespace=&quot;http://schemas.authz.org/cipl&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://schemas.authz.org/cipl&quot; xmlns:az=&quot;http://schemas.authz.org/capl&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:import namespace=&quot;http://schemas.authz.org/capl&quot; /&gt;
        ///  &lt;xs:element name=&quot;IssuePolicy&quot; type=&quot;IssuePolicyType&quot; /&gt;
        ///  &lt;xs:complexType name=&quot;IssuePolicyType&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///      &lt;xs:element name=&quot;Transforms&quot; type=&quot;az:TransformsType&quot; /&gt;
        ///    &lt;/xs:sequence&gt;
        ///    &lt;xs:attribut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IssuePolicySchema {
            get {
                return ResourceManager.GetString("IssuePolicySchema", resourceCulture);
            }
        }
    }
}
