FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app


ARG UID=1000
RUN useradd -u $UID -ms /bin/bash moduleuser
USER moduleuser

EXPOSE 8877/tcp

ENTRYPOINT ["dotnet", "LogModule.dll"]
COPY . /app